/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InfoUserTCNSProps {
  trinhDoDaoTaoId: any;
  tinhNghiPhep: any;
  _id: string;
  ssoId: string;
  hoDem: string;
  ten: string;
  ngaySinh: Date;
  maCanBo: string;
  tenGoiKhac: any;
  biDanh: any;
  trangThai: string;
  gioiTinh: string;
  email: string;
  noiSinhThanhPhoMa: string;
  noiSinhThanhPhoTen: string;
  noiSinhQuanMa: string;
  noiSinhQuanTen: string;
  noiSinhXaMa: string;
  noiSinhXaTen: string;
  viTriTuyenDungId: string;
  hinhThucTuyeDungId: string;
  queQuanThanhPhoMa: string;
  queQuanThanhPhoTen: string;
  queQuanQuanMa: string;
  queQuanQuanTen: string;
  queQuanXaMa: string;
  queQuanXaTen: string;
  hoKhauSoNha: string;
  hoKhauThanhPhoMa: string;
  hoKhauThanhPhoTen: string;
  hoKhauQuanMa: string;
  hoKhauQuanTen: string;
  hoKhauXaMa: string;
  hoKhauXaTen: string;
  noiOSoNha: string;
  noiOThanhPhoMa: string;
  noiOThanhPhoTen: string;
  noiOQuanMa: string;
  noiOQuanTen: string;
  noiOXaMa: string;
  noiOXaTen: string;
  sdtCaNhan: string;
  sdtNhaRieng: any;
  sdtCoQuan: any;
  ghiChu: any;
  fullName: any;
  quocTichId: any;
  danTocId: any;
  tonGiaoId: any;
  ngayVaoNganhYTe: any;
  cccdCMND: string;
  ngayCap: any;
  noiCap: any;
  tinhTrangHonNhanId: any;
  tenNganHang: any;
  chiNhanh: any;
  soTaiKhoan: any;
  soSoBHXH: string;
  noiCapBHXH: any;
  ngayCapBHXH: any;
  ngayThamGiaBHXH: any;
  ghiChuBHXH: any;
  maSoThue: any;
  ngayCapMaSoThue: any;
  listFileUrl: any;
  chieuCao: any;
  canNang: any;
  nhomMau: any;
  tinhTrangSucKhoe: any;
  laGiangVienCoHuu: any;
  chungChiSuPhamGiangVien: string;
  laChuyenVien: any;
  trinhDoGiaoDucPhoThongId: any;
  trinhDoLyLuanChinhTriId: any;
  trinhDoQuanLyHanhChinhId: any;
  trinhDoTinHocId: any;
  danhHieuPhongTangId: any;
  soTruongCongTac: any;
  ngoaiNguId: any;
  khungNangLucNgoaiNguId: any;
  ngayVaoDangDuBi: Date;
  ngayChinhThuc: Date;
  noiVaoDang: any;
  soTheDang: any;
  chucVuDangId: any;
  ngayNhapNgu: any;
  ngayXuatNgu: any;
  donViQuanDoi: any;
  chucVuQuanDoi: any;
  ngayVaoDoan: any;
  noiVaoDoan: any;
  soTheDoan: any;
  chucVuDoanId: any;
  ngayThamGiaCongDoan: any;
  noiThamGiaCongDoan: any;
  soTheCongDoan: any;
  hinhThucTuyenDungId: any;
  dotTuyenDungId: any;
  ngayTuyenDung: Date;
  soBaoDanh: any;
  ngayBatDauLamViec: any;
  ngayVaoNganh: any;
  emailCanBo: string;
  ngachTuyenDungId: any;
  donViViTriTuyenDungId: any;
  donViTuyenDungId: string;
  anhDaiDien: any;
  loaiHinhLamViec: any;
  trinhDoQuanLyNhaNuocId: any;
  urlAnhDaiDien: any;
  donViQuanLyId: any;
  donViChinhId: string;
  loaiHoSo: string;
  loaiHoSoKhac: any;
  laGiangVienNuocNgoai: any;
  coQuanChuQuan: any;
  soGiayPhepLaoDong: any;
  lichSuBanThanKhaiRo: any;
  lichSuBanThanThamGia: any;
  lichSuBanThanCoThanNhan: any;
  loaiCanBoGiangVien: string;
  chucDanhNgheNghiep: any;
  hang: any;
  maDanToc: string;
  namDuocPhong: any;
  ngayHuong: any;
  tenDanToc: string;
  maQuocTich: string;
  tenQuocTich: string;
  chucVuCongTac: any;
  donViDangCongTac: any;
  idDotCapNhat: any;
  maTonGiao: string;
  tenTonGiao: string;
  soHieuVienChuc: any;
  hocHam: any;
  hocVi: any;
  linhVucDaoTaoId: any;
  linhVucDaoTaoMa: any;
  soHochieu: any;
  toChucCuDen: any;
  thoiGianBatDauCuDen: any;
  thoiGianKetThucCuden: any;
  linhVuc: any;
  chuyenNganh: any;
  linhVucDaoTaoTen: any;
  tenNghiaVuDanQuanTuVe: any;
  ngayKetNapDanQuanTuVe: any;
  ngayHoanThanhNghiaVu: any;
  chucDanhDanQuanTuVe: any;
  soQuyetDinhHoanThanh: any;
  nguoiKyQuyetDinh: any;
  maHeThong: number;
  maDonViChinh: string;
  chucVuChinhId: string;
  maChucVuChinh: string;
  chatLuongNhanSu: string;
  namKyHopDong: any;
  maHoSo: any;
  conViTriChucDanhCoHieuLuc: boolean;
  donViViTriId: string;
  maNoiBo: string;
  khac: any;
  tenDonViTuyenDung: any;
  tenDonViViTriTuyenDung: any;
  viTriUngTuyen: any;
  banGoc: boolean;
  chucDanhGiangVienId: any;
  trangThaiChinhSua: string;
  trangThaiHoSoUngTuyen: any;
  ngachLuongId: any;
  hoTen: string;
  thoiGianGuiDuyet: any;
  ngayBatDauLamViecTaiTruong: any;
  yeuCauChinhSua: any;
  urlFileMinhChung: any;
  taiLieuUngTuyen: any;
  sinhMaHeThong: boolean;
  createdAt: Date;
  updatedAt: Date;
  danhSachDonViCanBoViTri: DanhSachDonViCanBoViTri[];
  trinhDoLyLuanChinhTri: any;
  trinhDoQuanLyHanhChinh: any;
  danhSachThongTinTrinhDoDaoTao: DanhSachThongTinTrinhDoDAOTAO[];
  danhSachHocHam: any[];
  danhSachDienBienLuong: DanhSachDienBienLuong[];
  chucVuDang: any;
  chucVuDoan: any;
  hinhThucTuyenDung: any;
  donViTuyenDung: DonVi;
  danhSachQuaTrinhCuDiCongTac: any[];
  danhSachQuanHeGiaDinhVeBanThan: DanhSachQuanHeGiaDinhVeBanThan[];
  trinhDoQuanLyNhaNuoc: any;
  donViViTriTuyenDung: any;
  donViChinh: DonVi;
  donViQuanLy: any;
  tinhTrangHonNhan: any;
  ngachTuyenDung: any;
  diemTuyenDung: any;
  dotTuyenDung: any;
  chucVuChinh: ChucVuChinh;
  donViViTri: DonViViTri;
  chucDanhGiangVien: any;
  ngachLuong: any;
  danhSachKhenThuong: { [key: string]: null | string }[];
  danhSachKyLuat: DanhSachKyLuat[];
  danhSachQuaTrinhDaoTaoBoiDuong: any[];
  danhSachQuaTrinhCongTac: DanhSachQuaTrinhCongTac[];
  danhSachQuanHeGiaDinhVeBenVoChong: DanhSachQuanHeGiaDinhVeBenVoChong[];
  danhSachThongTinTinHoc: any[];
  danhSachThongTinNgoaiNgu: any[];
  danhSachThongTinTrinhDoLyLuanChinhTri: any[];
  danhSachThongTinTrinhDoQuanLyHanhChinh: any[];
  danhSachThongTinTrinhDoQuanLyNhaNuoc: any[];
  danhSachBoiDuongQuocPhongAnNinh: any[];
}

export interface ChucVuChinh {
  ma: string;
  ten: string;
  _id: string;
}

export interface DanhSachDienBienLuong {
  _id: string;
  thongTinNhanSuId: string;
  idGoc: any;
  idDotXetNangLuong: any;
  ngachLuongId: string;
  bacLuongId: string;
  heSo: number;
  phanTramHuong: number;
  phuCapThamNien: any;
  phuCapVuotKhung: any;
  phuCapChucVu: any;
  phuCapDocHai: any;
  luongThoaThuan: any;
  chieuHuong: any;
  loaiNangLuong: any;
  nguyenNhan: any;
  loaiLuong: string;
  soQuyetDinh: any;
  fileDinhKem: string;
  ngayQuyetDinh: any;
  mocXetNangLuong: Date;
  tuNgay: Date;
  denNgay: Date;
  denNgayBackUp: Date;
  dieuChinh: number;
  ssoId: string;
  daXetDuyet: boolean;
  isHoiDongXetDuyet: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface DanhSachDonViCanBoViTri {
  _id: string;
  thongTinNhanSuId: string;
  donViId: string;
  chucVuId: string;
  donViViTriId: string;
  conHieuLuc: boolean;
  idGoc: null | string;
  soQuyetDinh: null | string;
  ngayQuyetDinh: Date | any;
  hieuLucTuNgay: Date | any;
  hieuLucDenNgay: Date | any;
  laDonViChinh: boolean;
  loaiQuyetDinh: null | string;
  urlFileUpload: null | string;
  createdAt: Date;
  updatedAt: Date;
  chucVu: ChucVu;
  donVi: DonVi;
  donViViTri: DonViViTri;
}

export interface ChucVu {
  ma: string;
  ten: string;
}

export interface DonVi {
  maDonVi: string;
  ten: string;
}

export interface DonViViTri {
  tenChucVu: string;
  capChucVu: string;
  _id: string;
}

export interface DanhSachKyLuat {
  _id: string;
  thongTinNhanSuId: string;
  idGoc: any;
  capKyLuatId: string;
  hinhThucKyLuatId: string;
  soQuyetDinh: string;
  coQuanQuyetDinh: string;
  nguoiKy: null | string;
  ngayQuyetDinh: Date;
  ngayKy: Date | any;
  daXetDieuChinhTangLuong: boolean;
  noiDung: null | string;
  urlFileUpload: null | string;
  cccd: string;
  hoTen: string;
  tenDonVi: any;
  ngayKyFormat: string;
  ngayQuyetDinhFormat: string;
  phuongThucKyLuatI: any;
  hinhThucKyLuatI: string;
  loaiKyLuatI: any;
  capKyLuatI: string;
  thoiGianDieuChinh: number | any;
  anhHuongThoiGianKyLuat: boolean | any;
  anhHuongThoiGianTamThoi: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface DanhSachQuaTrinhCongTac {
  _id: string;
  thongTinNhanSuId: string;
  idGoc: any;
  tuThagNam: Date;
  denThangNam: Date;
  donViCongTac: string;
  chucDanh: string;
  chucVu: string;
  fileDinhKem: string;
  noiDung: string;
  loaiQuyetDinh: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface DanhSachQuanHeGiaDinhVeBanThan {
  _id: string;
  thongTinNhanSuId: string;
  idGoc: any;
  hoVaTen: string;
  soDienThoai: any;
  namSinh: number;
  moiQuanHe: string;
  noiDung: string;
  nguoiPhuThuoc: boolean;
  ngheNghiep: string;
  noiCongTac: string;
  thangSinh: number;
  ngaySinh: number;
  cccdCMND: string;
  ngayCap: Date;
  noiCap: string;
  noiThuongTru: string;
  hoKhauSoNha: string;
  hoKhauThanhPhoMa: string;
  hoKhauThanhPhoTen: string;
  hoKhauQuanMa: string;
  hoKhauQuanTen: string;
  hoKhauXaMa: string;
  hoKhauXaTen: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface DanhSachQuanHeGiaDinhVeBenVoChong {
  _id: string;
  thongTinNhanSuId: string;
  idGoc: any;
  hoVaTen: string;
  namSinh: number;
  moiQuanHe: string;
  noiDung: string;
  nguoiPhuThuoc: boolean;
  ngheNghiep: string;
  noiCongTac: string;
  soDienThoai: any;
  thangSinh: number;
  ngaySinh: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface DanhSachThongTinTrinhDoDAOTAO {
  _id: string;
  thongTinNhanSuId: string;
  idGoc: string;
  trinhDoDaoTaoId: string;
  nganh: string;
  maNganh: string;
  noiDaoTao: any;
  namTotNghiep: any;
  hinhThucDaoTaoId: any;
  vanBangChungChi: any;
  coSoDaoTao: any;
  nuocDaoTao: any;
  fileDinhKem: any;
  thoiGianBatDau: any;
  thoiGianKetThuc: any;
  createdAt: Date;
  updatedAt: Date;
  trinhDoDaoTao: TrinhDoDAOTAO;
}

export interface TrinhDoDAOTAO {
  _id: string;
  ma: string;
  ten: string;
  soThuTu: number;
  moTa: any;
  suDung: any;
  createdAt: Date;
  updatedAt: Date;
}
