import { StyleSheet } from 'react-native';

import R from '@assets/R';
import { getFontSize, getLineHeight, HEIGHT, WIDTH } from '@common';

const styles = StyleSheet.create({
  textLuuY: {
    textAlign: 'justify',
    fontFamily: R.fonts.BeVietnamProItalic,
    color: R.colors.redColor,
    lineHeight: getLineHeight(22),
    paddingHorizontal: WIDTH(16),
  },
  text: {
    fontFamily: R.fonts.BeVietnamProRegular,
    color: '#8199D7',
  },
  viewContainer: {
    paddingTop: HEIGHT(24),
  },
  containerHeader: {
    alignItems: 'flex-end',
    marginBottom: HEIGHT(16),
  },
  viewFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: HEIGHT(4),
    // height: 100,
  },
  buttonSubmit: {
    backgroundColor: R.colors.white,
    borderWidth: 1,
    paddingVertical: HEIGHT(12),
    // paddingHorizontal: WIDTH(20),
    width: WIDTH(160),
    borderColor: R.colors.colorMain,
  },
  buttonGui: {
    backgroundColor: R.colors.colorMain,
    borderWidth: 1,
    paddingVertical: HEIGHT(12),
    // paddingHorizontal: WIDTH(20),
    width: WIDTH(160),
    borderColor: R.colors.colorMain,
  },
  textButton: {
    color: R.colors.colorMain,
  },
  textButtonGui: {
    color: R.colors.white,
  },
  hitSlop: {
    top: 15,
    left: 15,
    right: 15,
    bottom: 15,
  },
  contentFlatlist: {
    paddingHorizontal: WIDTH(16),
    paddingBottom: HEIGHT(30),
  },
  tieuChiNho: {
    flex: 1,
    marginRight: WIDTH(16),
    fontSize: getFontSize(14),
    color: R.colors.grayText,
    fontFamily: R.fonts.BeVietnamProRegular,
    lineHeight: getLineHeight(20),
    textAlign: 'justify',
  },

  textTieuChi: {
    textAlign: 'justify',
    flex: 1,
    marginRight: WIDTH(16),
    color: R.colors.black0,
    fontSize: getFontSize(14),
    fontFamily: R.fonts.BeVietnamProSemiBold,
    lineHeight: getLineHeight(22),
  },
  containerItem: {
    marginTop: HEIGHT(16),
    paddingBottom: HEIGHT(16),
    borderBottomWidth: 0.5,
    borderColor: 'rgba(171, 171, 171, 0.4)',
  },
  viewItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  viewForm: {
    marginTop: HEIGHT(12),
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewInput: {
    borderWidth: 0.5,
    borderColor: 'rgba(171, 171, 171, 0.4)',
    backgroundColor: R.colors.white,
    borderRadius: WIDTH(2),
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  dropdown: {
    fontSize: getFontSize(14),
    color: R.colors.black0,
    lineHeight: getLineHeight(18),
    flex: 0,
    fontFamily: R.fonts.BeVietnamProRegular,
  },
  containerDropdown: {
    borderWidth: 0.5,
    borderColor: 'rgba(171, 171, 171, 0.4)',
    backgroundColor: R.colors.white,
    paddingVertical: HEIGHT(4),
    height: HEIGHT(40),
    paddingHorizontal: WIDTH(4),
    fontSize: getFontSize(12),
    fontFamily: R.fonts.BeVietnamProMedium,
    width: WIDTH(70),
    justifyContent: 'flex-end',
    // backgroundColor: '#bfbfbf',
    borderRadius: WIDTH(2),
  },
  viewDiemDanhGia: {
    backgroundColor: '#bfbfbf',
    borderRadius: WIDTH(2),
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    width: WIDTH(70),
    paddingVertical: HEIGHT(4),
    paddingHorizontal: WIDTH(4),
    height: HEIGHT(40),
  },
  diemDanhGia: {
    textAlign: 'center',
    color: R.colors.white,
    fontSize: getFontSize(14),
    fontFamily: R.fonts.BeVietnamProMedium,
  },
  input: {
    textAlign: 'center',
    paddingVertical: HEIGHT(4),
    color: R.colors.black0,
    paddingHorizontal: WIDTH(4),
    fontSize: getFontSize(14),
    fontFamily: R.fonts.BeVietnamProMedium,
    width: WIDTH(70),
    height: HEIGHT(40),
  },
  container: {
    flex: 1,
    backgroundColor: R.colors.backgroundColorNew,
  },
  divider: { width: WIDTH(310), alignSelf: 'center' },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    width: WIDTH(52),
    position: 'absolute',
    bottom: HEIGHT(100),
    right: WIDTH(16),
    height: WIDTH(52),
    backgroundColor: R.colors.primaryColor,
    borderRadius: 100,
  },
  containerStyle: {
    width: WIDTH(230),
    // height: HEIGHT(36),
    paddingLeft: WIDTH(8),
    borderRadius: WIDTH(8),
  },
  textInfo: {
    fontSize: getFontSize(14),
    color: R.colors.gray6B,
    lineHeight: getLineHeight(18),
    textAlign: 'right',
    // marginLeft: WIDTH(20),
    fontFamily: R.fonts.BeVietnamProRegular,
  },
  textInfoBoard: {
    fontSize: getFontSize(14),
    color: R.colors.black0,
    fontFamily: R.fonts.BeVietnamProRegular,
  },

  viewKQ: {
    width: WIDTH(343),
    marginBottom: HEIGHT(16),
  },
  textKQ: {
    textAlign: 'right',
    fontFamily: R.fonts.BeVietnamProMedium,
    fontSize: getFontSize(14),
  },
  listContainer: { marginTop: HEIGHT(16), paddingBottom: HEIGHT(40) },
  labelStyle: {
    fontSize: getFontSize(16),
    lineHeight: getLineHeight(24),
    fontFamily: R.fonts.BeVietnamProMedium,
  },
  tabContainer: {
    marginTop: HEIGHT(24),
    marginBottom: HEIGHT(20),
    height: HEIGHT(42),
    paddingHorizontal: WIDTH(16),
    justifyContent: 'center',
  },
  tabBar: {
    backgroundColor: R.colors.white,
    borderTopWidth: WIDTH(1),
    borderTopColor: R.colors.colorf8f8f8,
    overflow: 'hidden',
  },
  indicatorStyle: {
    height: HEIGHT(2),
    backgroundColor: R.colors.colorPink,
  },
  viewBoLoc: {
    width: WIDTH(343),
    alignSelf: 'center',
    // marginBottom: HEIGHT(12),
    // marginTop: HEIGHT(24),
  },
  viewLocKy: {
    // backgroundColor: R.colors.white,
    // borderRadius: WIDTH(8),
    paddingHorizontal: WIDTH(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: HEIGHT(16),
  },
  filterContainer: {
    borderRadius: WIDTH(8),
    backgroundColor: R.colors.white,
    width: WIDTH(343),
    alignSelf: 'center',
    marginBottom: HEIGHT(12),
    marginTop: HEIGHT(24),
  },
});

export default styles;
