const fonts = {
  icons: 'icons',
  // RobotoMedium: 'Roboto-Medium',
  // RobotoRegular: 'Roboto-Regular',
  // RobotoLight: 'Roboto-Light',
  // RobotoItalic: 'Roboto-Italic',
  // RobotoBold: 'Roboto-Bold',
  // Roboto: 'Roboto',
  BeVietnamProBlack: 'BeVietnamPro-Black',
  // BeVietnamProBlackItalic: 'BeVietnamPro-BlackItalic',
  BeVietnamProBold: 'BeVietnamPro-Bold',
  BeVietnamProBoldItalic: 'BeVietnamPro-BoldItalic',
  BeVietnamProExtraBold: 'BeVietnamPro-ExtraBold',
  BeVietnamProExtraBoldItalic: 'BeVietnamPro-ExtraBoldItalic',
  BeVietnamProExtraLight: 'BeVietnamPro-ExtraLight',
  BeVietnamProExtraLightItalic: 'BeVietnamPro-ExtraLightItalic',
  BeVietnamProItalic: 'BeVietnamPro-Italic',
  BeVietnamProLight: 'BeVietnamPro-Light',
  BeVietnamProLightItalic: 'BeVietnamPro-LightItalic',
  BeVietnamProMedium: 'BeVietnamPro-Medium',
  BeVietnamProMediumItalic: 'BeVietnamPro-MediumItalic',
  BeVietnamProRegular: 'BeVietnamPro-Regular',
  BeVietnamProSemiBold: 'BeVietnamPro-SemiBold',
  BeVietnamProSemiBoldItalic: 'BeVietnamPro-SemiBoldItalic',
  BeVietnamProThin: 'BeVietnamPro-Thin',
  BeVietnamProThinItalic: 'BeVietnamPro-ThinItalic',
};

export default fonts;
