/* eslint-disable @typescript-eslint/no-explicit-any */
import { CongNoProps } from '@features/CongNo/type';
import { LopHPSvList } from '@features/DangKyTinChi/KetQuaDangKyTinChi/type';
import {
  CauHinhLoaiHinhProps,
  DSKhaiBaoProps,
  LichSuKhaiBaoProps,
} from '@features/KhaiBaoQuyTrinh/type';
import { SinhVienLHCProps } from '@features/LopHanhChinhSV/ThongTinChungSV/type';
import {
  BieuMauKhaoSatProps,
  DotDGGVProps,
  InfoClassProps,
} from '@features/LopTinChi/ChiTietLopTinChi/type';
import {
  KetQuaKhaiBaoProps,
  LoaiHinhNCKHProps,
} from '@features/QuanLyKhoaHocV2/type';
import { VBHDProps } from '@features/VanBanHuongDan/DanhSachChiTietVanBanHuongDan';
import { DataCalendarProps } from '@features/VanPhongSo/LichTuanHocVien/component/ModalCalendarWeekProps';
import { ThongTinCDRProps } from '@features/XetTotNghiep/type';
import { AccountProps } from '@model/app';
import { RegisterNavigationParams } from '@model/navigation-params';
import { StackScreenProps as RNStackScreenProps } from '@react-navigation/stack';

export enum APP_SCREEN {
  UN_AUTHORIZE = 'UN_AUTHORIZE',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  AUTHORIZE = 'AUTHORIZE',
  HOME = 'HOME',
  INTRO = 'INTRO',
  SIGNIN = 'SIGNIN',
  TABMAIN = 'TABMAIN',
  GOCHOCTAP = 'GOCHOCTAP',
  TINTUC = 'TINTUC',
  TINTUCV2 = 'TINTUCV2',
  CHITIETTINTUC = 'CHITIETTINTUC',
  CHITIETTINTUCV2 = 'CHITIETTINTUCV2',
  WELCOME = 'WELCOME',
  LOPHANHCHINHSV = 'LOPHANHCHINHSV',
  THONGTINCHUNGSV = 'THONGTINCHUNGSV',
  GUITHONGBAO = 'GUITHONGBAO',
  SEEPDF = 'SEEPDF',
  CHITIETDONDV1C = 'CHITIETDONDV1C',
  DETAILNOTI = 'DETAILNOTI',
  LOPTINCHI = 'LOPTINCHI',
  CHITIETLOPTINCHI = 'CHITIETLOPTINCHI',
  THONGTINCHUNGLTC = 'THONGTINCHUNGLTC',
  THONGTINBUOIHOC = 'THONGTINBUOIHOC',
  CHITIETBUOIHOC = 'CHITIETBUOIHOC',
  BUOIHOCGIANGVIEN = 'BUOIHOCGIANGVIEN',
  KETQUAHOCTAP = 'KETQUAHOCTAP',
  CONGNO = 'CONGNO',
  CHITIETCONGNO = 'CHITIETCONGNO',
  PHANHOI = 'PHANHOI',
  THONGTINPHANHOI = 'THONGTINPHANHOI',
  DCHPGIANGVIEN = 'DCHPGIANGVIEN',
  MAYTINHTHONGMINH = 'MAYTINHTHONGMINH',
  DCHPTHONGTINCHUNG = 'DCHPTHONGTINCHUNG',
  DCHPLICHTRINH = 'DCHPLICHTRINH',
  THUVIEN = 'THUVIEN',
  QRSCANNER = 'QRSCANNER',
  THEMDONPHANHOI = 'THEMDONPHANHOI',
  TRANGCANHAN = 'TRANGCANHAN',
  TIENTRINHHOCTAP = 'TIENTRINHHOCTAP',
  KETQUAHOCTAPMAIN = 'KETQUAHOCTAPMAIN',
  CHITIETDANGKYSACHED = 'CHITIETDANGKYSACHED',
  FILTERTINTUC = 'FILTERTINTUC',
  FILTERTINTUCV2 = 'FILTERTINTUCV2',
  LICHSUDIEMDANH = 'LICHSUDIEMDANH',
  HOCLIEUSO = 'HOCLIEUSO',
  THEMMOITABLE = 'THEMMOITABLE',
  THONGBAO = 'THONGBAO',
  GUITHACMACDIEM = 'GUITHACMACDIEM',
  CHITIETTHONGBAO = 'CHITIETTHONGBAO',
  CHITIETTHACMAC = 'CHITIETTHACMAC',
  HUONGDANHTHANHTOAN = 'HUONGDANHTHANHTOAN',
  VANBANHUONGDAN = 'VANBANHUONGDAN',
  DSCHITIETVANBANHUONGDAN = 'DSCHITIETVANBANHUONGDAN',
  GIOITHIEU = 'GIOITHIEU',
  DANHGIAGIANGVIEN = 'DANHGIAGIANGVIEN',
  LOPTHUCHANH = 'LOPTHUCHANH',
  CHITIETBANNER = 'CHITIETBANNER',
  THANHTOANTIEN = 'THANHTOANTIEN',
  GIOHANG = 'GIOHANG',
  LICHSUDATHANG = 'LICHSUDATHANG',
  TRANGCANHANP = 'TRANGCANHANP',
  CHITIETLICHSU = 'CHITIETLICHSU',
  CACHTHANHTOAN = 'CACHTHANHTOAN',
  KHUYENMAI = 'KHUYENMAI',
  CTKHUYENMAI = 'CTKHUYENMAI',
  LICHSUDIEM = 'LICHSUDIEM',
  MOTATHEMDIEM = 'MOTATHEMDIEM',
  MANCHITIET = 'MANCHITIET',
  ABOUTUS = 'ABOUTUS',
  KHAOSATTRUCTUYEN = 'KHAOSATTRUCTUYEN',
  ADDEVENTCALENDAR = 'ADDEVENTCALENDAR',
  NOIDUNGBUOIHOC = 'NOIDUNGBUOIHOC',
  THONGTINSINHVIEN = 'THONGTINSINHVIEN',
  THONGTINSINHVIENLHC = 'THONGTINSINHVIENLHC',
  KETQUAHOCTAPSV = 'KETQUAHOCTAPSV',
  CHITIETDIEMCONG = 'CHITIETDIEMCONG',
  THONGBAOGV = 'THONGBAOGV',
  DECUONGHOCPHAN = 'DECUONGHOCPHAN',
  TAOTHONGBAOGIANGVIEN = 'TAOTHONGBAOGIANGVIEN',
  LOPHANHCHINHGV = 'LOPHANHCHINHGV',
  CHITIETLOPHC = 'CHITIETLOPHC',
  THONGTINCHUNGLOPHC = 'THONGTINCHUNGLOPHC',
  THONGKEGIOGIANG = 'THONGKEGIOGIANG',
  THACMACDIEMLTC = 'THACMACDIEMLTC',
  SEARCHSCREEN = 'SEARCHSCREEN',
  LICHTUANHOCVIEN = 'LICHTUANHOCVIEN',
  LICHSINHNHAT = 'LICHSINHNHAT',
  CAUHOITHUONGGAP = 'CAUHOITHUONGGAP',
  DANHSACHTINTUCV2 = 'DANHSACHTINTUCV2',
  HOSONHANSU = 'HOSONHANSU',
  QUANLYKHOAHOC = 'QUANLYKHOAHOC',
  QUANLYKHOAHOCV2 = 'QUANLYKHOAHOCV2',
  THONGKEQLKH = 'THONGKEQLKH',
  THUCHIENDETAI = 'THUCHIENDETAI',
  CHITIETDETAI = 'CHITIETDETAI',
  DANGKYDETAI = 'DANGKYDETAI',
  HUONGDANNCSHVCH = 'HUONGDANNCSHVCH',
  ADDHUONGDAN = 'ADDHUONGDAN',
  SEARCHNS = 'SEARCHNS',
  THEMMOINS = 'THEMMOINS',
  THEMMOIMC = 'THEMMOIMC',
  LYLICH = 'LYLICH',
  EDITLYLICH = 'EDITLYLICH',
  XEMCHITIETKHAIBAO = 'XEMCHITIETKHAIBAO',
  ADDFROMLIB = 'ADDFROMLIB',
  THEMMOILYLICH = 'THEMMOILYLICH',
  QUANLYNCKHLV1 = 'QUANLYNCKHLV1',
  QUANLYNCKHLV2 = 'QUANLYNCKHLV2',
  QUANLYNCKHLV3 = 'QUANLYNCKHLV3',
  THEMMOITCNS = 'THEMMOITCNS',
  GUIBANCHINHSUA = 'GUIBANCHINHSUA',
  SWITCHROLE = 'SWITCHROLE',
  MONTUCHON = 'MONTUCHON',
  XETTOTNGHIEP = 'XETTOTNGHIEP',
  CHITIETCDR = 'CHITIETCDR',
  THOIKHOABIEUV2 = 'THOIKHOABIEUV2',
  KHAIBAOQUYTRINH = 'KHAIBAOQUYTRINH',
  CACBUOCKHAIBAO = 'CACBUOCKHAIBAO',
  SEARCHTCNSCANBO = 'SEARCHTCNSCANBO',
  ADDTABLE = 'ADDTABLE',
  VIEWTABLE = 'VIEWTABLE',
  SANPHAMHOATDONG = 'SANPHAMHOATDONG',
  VIEWRENDERNCKH = 'VIEWRENDERNCKH',
  ADDMEMBERNCKH = 'ADDMEMBERNCKH',
  FILTERCAUHOITHUONGGAP = 'FILTERCAUHOITHUONGGAP',
  DANHSACHKHAIBAONCKH = 'DANHSACHKHAIBAONCKH',
  DETAILTSANPHAM = 'DETAILTSANPHAM',
  VITRICHUCDANHTABLE = 'VITRICHUCDANHTABLE',
  VITRIQUYHOACHTABLE = 'VITRIQUYHOACHTABLE',
  QUATRINHCONGTACTABLE = 'QUATRINHCONGTACTABLE',
  DIENBIENLUONGTABLE = 'DIENBIENLUONGTABLE',
  DIENBIENPHUCAPTABLE = 'DIENBIENPHUCAPTABLE',
  DIENBIENKHOANTABLE = 'DIENBIENKHOANTABLE',
  DIENBIENPHUCAPTANGTHEMTABLE = 'DIENBIENPHUCAPTANGTHEMTABLE',
  KHENTHUONGTABLE = 'KHENTHUONGTABLE',
  KYLUATTABLE = 'KYLUATTABLE',
  GIADINHMETABLE = 'GIADINHMETABLE',
  GIADINHVOTABLE = 'GIADINHVOTABLE',
  DOITUONGCHINHSACHTABLE = 'DOITUONGCHINHSACHTABLE',
  HOCHAMTABLE = 'HOCHAMTABLE',
  TRINHDODAOTAOTABLE = 'TRINHDODAOTAOTABLE',
  LYLUANCHINHTRITABLE = 'LYLUANCHINHTRITABLE',
  QUANLYHANHCHINHTABLE = 'QUANLYHANHCHINHTABLE',
  QUANLYNHANUOCTABLE = 'QUANLYNHANUOCTABLE',
  NGOAINGUTABLE = 'NGOAINGUTABLE',
  TINHOCTABLE = 'TINHOCTABLE',
  QUOCPHONGANNINHTABLE = 'QUOCPHONGANNINHTABLE',
  QUATRINHDTBDTABLE = 'QUATRINHDTBDTABLE',
  THONGKENCKH = 'THONGKENCKH',
  DANGKYTINCHI = 'DANGKYTINCHI',
  LICHHOCTINCHI = 'LICHHOCTINCHI',
  TOCHUCNHANSU = 'TOCHUCNHANSU',
  QUATRINHCUDICONGTAC = 'QUATRINHCUDICONGTAC',
  QUATRINHCUDIDTBD = 'QUATRINHCUDIDTBD',
  KEKHAITAISAN = 'KEKHAITAISAN',
  DETAILKEKHAI = 'DETAILKEKHAI',
  VIEWADDKEKHAI = 'VIEWADDKEKHAI',
  DANHGIACANHAN = 'DANHGIACANHAN',
  DANHGIADONVI = 'DANHGIADONVI',
  DETAILDANHGIACANHAN = 'DETAILDANHGIACANHAN',
  PHIEUTONGHOPKETQUA = 'PHIEUTONGHOPKETQUA',
  ADDNEWCALENDAR = 'ADDNEWCALENDAR',
  THANHTOANCONGNO = 'THAHTOANCONGNO',
  KEHOACHNAM = 'KEHOACHNAM',
  KEHOACHHOATDONG = 'KEHOACHHOATDONG',
  DSKEHOACHHOATDONG = 'DSKEHOACHHOATDONG',
  CHITIETKEHOACHHOATDONG = 'CHITIETKEHOACHHOATDONG',
  DANHGIABUOIHOC = 'DANHGIABUOIHOC',
  DANGKYDAYBU = 'DANGKYDAYBU',
  LICHSUDAYBU = 'LICHSUDAYBU',
  BANGCHAMCONG = 'BANGCHAMCONG',
  DANGKYKYTUCXA = 'DANGKYKYTUCXA',
  KYTUCXA = 'KYTUCXA',
  ADDDANGKYKYTUCXA = 'ADDDANGKYKYTUCXA',
  COSOVATCHAT = 'COSOVATCHAT',
  TAISANVATTU = 'TAISANVATTU',
  CHITIETTAISANVATTU = 'CHITIETTAISANVATTU',
  KIEMKETAISAN = 'KIEMKETAISAN',
  PHONGKIEMKETAISAN = 'PHONGKIEMKETAISAN',
  DSTAISANKIEMKE = 'DSTAISANKIEMKE',
  LICHTHI = 'LICHTHI',
  DIEMRENLUYEN = 'DIEMRENLUYEN',
  SEARCHQLDTSINHVIEN = 'SEARCHQLDTSINHVIEN',
  CONGVIEC = 'CONGVIEC',
  CHITIETCONGVIEC = 'CHITIETCONGVIEC',
  LICHSUTIENDOCONGVIEC = 'LICHSUTIENDOCONGVIEC',
  THEMMOIQUATRINHCUDIDTBD = 'THEMMOIQUATRINHCUDIDTBD',
  HOPDONG = 'HOPDONG',
  CHITIETHOPDONG = 'CHITIETHOPDONG',
  BANGLAMTHEMGIO = 'BANGLAMTHEMGIO',
  DANGKYTINCHISINHVIEN = 'DANGKYTINCHISINHVIEN',
  CHITIETHOCPHAN = 'CHITIETHOCPHAN',
  XEMTRUOCLICHLTC = 'XEMTRUOCLICHLTC',
  SUKIENTHAMGIA = 'SUKIENTHAMGIA',
  THIETLAPMAULICH = 'THIETLAPMAULICH',
  DALUU = 'DALUU',
  DANHSACHDONXINNGHI = 'DANHSACHDONXINNGHI',
  CHITIETPHIEUDIEM = 'CHITIETPHIEUDIEM',
  THEMMOIMINHCHUNG = 'THEMMOIMINHCHUNG',
  SUKIENDATHAMGIA = 'SUKIENDATHAMGIA',
  KHAOSATSUKIEN = 'KHAOSATSUKIEN',
  THEMMOILICHLAMTHEMGIO = 'THEMMOILICHLAMTHEMGIO',
  THEMMOIDANHSACHLAMTHEM = 'THEMMOIDANHSACHLAMTHEM',
  THEMMOIDANHSACHHOCLIEU = 'THEMMOIDANHSACHHOCLIEU',
  DIENDAN = 'DIENDAN',
  BINHLUAN = 'BINHLUAN',
  CHITIETBAIDANG = 'CHITIETBAIDANG',
  GIOITHIEULOPTINCHI = 'GIOITHIEULOPTINCHI',
  BAITAPVENHA = 'BAITAPVENHA',
  CHITIETBAITAP = 'CHITIETBAITAP',
  KHAOSATBAITAP = 'KHAOSATBAITAP',
  BAITAPVENHASINHVIEN = 'BAITAPVENHASINHVIEN',
  THONGTINBAITAP = 'THONGTINBAITAP',
}

export type RootStackParamList = {
  [APP_SCREEN.HOCHAMTABLE]: any;
  [APP_SCREEN.BAITAPVENHA]: any;
  [APP_SCREEN.THIETLAPMAULICH]: any;
  [APP_SCREEN.SUKIENTHAMGIA]: any;
  [APP_SCREEN.GIOITHIEULOPTINCHI]: any;
  [APP_SCREEN.XEMTRUOCLICHLTC]: any;
  [APP_SCREEN.THANHTOANCONGNO]: any;
  [APP_SCREEN.DIENDAN]: any;
  [APP_SCREEN.DANGKYTINCHISINHVIEN]: any;
  [APP_SCREEN.CHITIETHOCPHAN]: any;
  [APP_SCREEN.DANGKYDAYBU]: any;
  [APP_SCREEN.ADDNEWCALENDAR]: {
    onRefresh?: () => void;
    dataDefault?: DataCalendarProps;
  };
  [APP_SCREEN.LICHHOCTINCHI]: {
    listMonHoc: LopHPSvList[];
  };
  [APP_SCREEN.DETAILKEKHAI]: {
    data: any;
    onRefresh: () => void;
  };
  [APP_SCREEN.DETAILDANHGIACANHAN]: {
    data: any;
    isDisabled: boolean;
    onRefresh: () => void;
    dataDonVi?: any;
    donVi?: boolean;
    thongTinNhanSu?: AccountProps;
    bieuMau?: any;
  };
  [APP_SCREEN.VIEWADDKEKHAI]: any;
  [APP_SCREEN.DANHGIADONVI]: any;
  [APP_SCREEN.BUOIHOCGIANGVIEN]: any;
  [APP_SCREEN.DIEMRENLUYEN]: any;
  [APP_SCREEN.PHIEUTONGHOPKETQUA]: {
    dsNhanSu: any;
    idDot: string;
    onRefresh: () => void;
  };
  [APP_SCREEN.DANHGIACANHAN]: any;
  [APP_SCREEN.TRINHDODAOTAOTABLE]: any;
  [APP_SCREEN.LYLUANCHINHTRITABLE]: any;
  [APP_SCREEN.QUANLYHANHCHINHTABLE]: any;
  [APP_SCREEN.QUANLYNHANUOCTABLE]: any;
  [APP_SCREEN.DANGKYTINCHI]: any;
  [APP_SCREEN.NGOAINGUTABLE]: any;
  [APP_SCREEN.TINHOCTABLE]: any;
  [APP_SCREEN.THONGKENCKH]: any;
  [APP_SCREEN.QUOCPHONGANNINHTABLE]: any;
  [APP_SCREEN.QUATRINHDTBDTABLE]: any;
  [APP_SCREEN.DCHPGIANGVIEN]: any;
  [APP_SCREEN.LOGIN]: undefined;
  [APP_SCREEN.REGISTER]: RegisterNavigationParams;
  [APP_SCREEN.UN_AUTHORIZE]: undefined;
  [APP_SCREEN.AUTHORIZE]: undefined;
  [APP_SCREEN.HOME]: undefined;
  [APP_SCREEN.LYLICH]: any;
  [APP_SCREEN.QUANLYKHOAHOC]: any;
  [APP_SCREEN.QUANLYKHOAHOCV2]: any;
  [APP_SCREEN.VITRICHUCDANHTABLE]: any;
  [APP_SCREEN.VITRIQUYHOACHTABLE]: any;
  [APP_SCREEN.GIADINHVOTABLE]: any;
  [APP_SCREEN.KYLUATTABLE]: any;
  [APP_SCREEN.GIADINHMETABLE]: any;
  [APP_SCREEN.DOITUONGCHINHSACHTABLE]: any;
  [APP_SCREEN.KHENTHUONGTABLE]: any;
  [APP_SCREEN.DIENBIENPHUCAPTABLE]: any;
  [APP_SCREEN.DIENBIENKHOANTABLE]: any;
  [APP_SCREEN.DIENBIENPHUCAPTANGTHEMTABLE]: any;
  [APP_SCREEN.QUATRINHCONGTACTABLE]: any;
  [APP_SCREEN.DIENBIENLUONGTABLE]: any;
  [APP_SCREEN.DETAILTSANPHAM]: {
    dataLoaiHinh?: LoaiHinhNCKHProps;
    data: KetQuaKhaiBaoProps;
  };
  [APP_SCREEN.VIEWRENDERNCKH]: {
    dataLoaiHinh?: LoaiHinhNCKHProps;
    dotId?: string;
    data?: KetQuaKhaiBaoProps;
    onRefresh: () => void;
  };
  [APP_SCREEN.THEMMOINS]: any;
  [APP_SCREEN.DANHSACHKHAIBAONCKH]: {
    dataLoaiHinh: LoaiHinhNCKHProps;
  };
  [APP_SCREEN.MONTUCHON]: any;
  [APP_SCREEN.THOIKHOABIEUV2]: any;
  [APP_SCREEN.HUONGDANNCSHVCH]: any;
  [APP_SCREEN.THONGKEQLKH]: any;
  [APP_SCREEN.ADDHUONGDAN]: any;
  [APP_SCREEN.THEMMOITCNS]: any;
  [APP_SCREEN.QUANLYNCKHLV1]: any;
  [APP_SCREEN.QUANLYNCKHLV2]: any;
  [APP_SCREEN.QUANLYNCKHLV3]: any;
  [APP_SCREEN.HOSONHANSU]: any;
  [APP_SCREEN.SWITCHROLE]: any;
  [APP_SCREEN.SEARCHNS]: any;
  [APP_SCREEN.XETTOTNGHIEP]: any;
  [APP_SCREEN.XEMCHITIETKHAIBAO]: any;
  [APP_SCREEN.THEMMOIMC]: any;
  [APP_SCREEN.THUCHIENDETAI]: any;
  [APP_SCREEN.DANGKYDETAI]: any;
  [APP_SCREEN.EDITLYLICH]: any;
  [APP_SCREEN.INTRO]: any;
  [APP_SCREEN.ADDFROMLIB]: any;
  [APP_SCREEN.THEMMOILYLICH]: any;
  [APP_SCREEN.CHITIETDETAI]: any;
  [APP_SCREEN.DECUONGHOCPHAN]: {
    infoClass: InfoClassProps | undefined;
    dataTienTrinh?: any;
  };
  [APP_SCREEN.MAYTINHTHONGMINH]: any;
  [APP_SCREEN.DCHPLICHTRINH]: any;
  [APP_SCREEN.DCHPTHONGTINCHUNG]: any;
  [APP_SCREEN.SIGNIN]: undefined;
  [APP_SCREEN.TABMAIN]: undefined;
  [APP_SCREEN.GOCHOCTAP]: undefined;
  [APP_SCREEN.TINTUC]: undefined;
  [APP_SCREEN.TINTUCV2]: undefined;
  [APP_SCREEN.LICHTHI]: undefined;
  [APP_SCREEN.DANHSACHTINTUCV2]: any;
  [APP_SCREEN.SANPHAMHOATDONG]: { item: { title: string } };
  [APP_SCREEN.ADDMEMBERNCKH]: {
    index?: number | undefined;
    dataInit?: any;
    loaiHinh?: LoaiHinhNCKHProps;
    getData: (e: any, index: number | undefined) => void;
    delItem: (index: number) => void;
  };
  [APP_SCREEN.FILTERCAUHOITHUONGGAP]?: any;
  [APP_SCREEN.CHITIETCDR]: { data: ThongTinCDRProps };
  [APP_SCREEN.CHITIETTINTUC]: {
    content: any;
    isFromNoticeScreen?: boolean;
    idTinTuc?: string;
  };
  [APP_SCREEN.CHITIETTINTUCV2]: {
    content: any;
    isFromNoticeScreen?: boolean;
    idTinTuc?: string;
  };
  [APP_SCREEN.WELCOME]: undefined;
  [APP_SCREEN.LOPHANHCHINHSV]?: {
    funGoBack?: () => void;
    fromDetailNotiScreen?: boolean;
    isFromOutside?: boolean;
  };
  [APP_SCREEN.THONGTINCHUNGSV]: any;
  [APP_SCREEN.GUITHONGBAO]: any;
  [APP_SCREEN.SEEPDF]: {
    content?: { sourcePDF?: string; title?: string };
  };
  [APP_SCREEN.CHITIETDONDV1C]: any;
  [APP_SCREEN.DETAILNOTI]: any;
  [APP_SCREEN.LOPTINCHI]: any;
  [APP_SCREEN.CHITIETLOPTINCHI]: any;
  [APP_SCREEN.THONGTINCHUNGLTC]: any;
  [APP_SCREEN.THONGTINBUOIHOC]: any;
  [APP_SCREEN.KETQUAHOCTAP]: any;
  [APP_SCREEN.CHITIETBUOIHOC]: any;
  [APP_SCREEN.THEMDONPHANHOI]: any;
  [APP_SCREEN.CHITIETCONGNO]: {
    itemInfo: CongNoProps;
    onRefreshList: () => void;
  };
  [APP_SCREEN.CONGNO]: undefined;
  [APP_SCREEN.PHANHOI]: undefined;
  [APP_SCREEN.THONGTINPHANHOI]: any;
  [APP_SCREEN.TRANGCANHAN]: any;
  [APP_SCREEN.FILTERTINTUC]: any;
  [APP_SCREEN.FILTERTINTUCV2]: any;
  [APP_SCREEN.LICHSUDIEMDANH]: any;
  [APP_SCREEN.THEMMOITABLE]: any;
  [APP_SCREEN.HOCLIEUSO]: any;
  [APP_SCREEN.THUVIEN]: undefined;
  [APP_SCREEN.QRSCANNER]: any;
  [APP_SCREEN.LICHSINHNHAT]: any;
  [APP_SCREEN.SEARCHSCREEN]: any;
  [APP_SCREEN.TIENTRINHHOCTAP]: undefined;
  [APP_SCREEN.KETQUAHOCTAPMAIN]: undefined;
  [APP_SCREEN.CHITIETDANGKYSACHED]: undefined;
  [APP_SCREEN.GUITHACMACDIEM]: any;
  [APP_SCREEN.CHITIETTHACMAC]: any;
  [APP_SCREEN.CHITIETTHONGBAO]: {
    idNoti?: string;
    notiType?: number;
    hideDetailBtn?: boolean;
    funGoBack?: () => void;
    item?: any;
  };
  [APP_SCREEN.VANBANHUONGDAN]: any;
  [APP_SCREEN.DSCHITIETVANBANHUONGDAN]: {
    item: { ten: string; danhSachTep: VBHDProps[] };
  };
  [APP_SCREEN.GIOITHIEU]: any;
  [APP_SCREEN.LOPTHUCHANH]: any;
  [APP_SCREEN.DANHGIAGIANGVIEN]: {
    data: BieuMauKhaoSatProps;
    giangVien?: {
      maLop: string;
      lopHocPhanId: string;
      giangVienSsoId: string;
      maGiangVien: string;
      hoTenGiangVien: string;
      vaiTroNguoiKhaoSat: string;
    };
    idKhaoSat: string;
    initKetQua?: any;
    disabled?: boolean;
    refreshData?: () => void;
    idDot: string;
    dot?: DotDGGVProps;
    isTietHoc?: boolean;
    hasEnd?: boolean;
  };
  [APP_SCREEN.CHITIETBANNER]: any;
  [APP_SCREEN.THANHTOANTIEN]: any;
  [APP_SCREEN.GIOHANG]: any;
  [APP_SCREEN.LICHSUDATHANG]: any;
  [APP_SCREEN.TRANGCANHANP]: any;
  [APP_SCREEN.CHITIETLICHSU]: any;
  [APP_SCREEN.CACHTHANHTOAN]: any;
  [APP_SCREEN.KHUYENMAI]: any;
  [APP_SCREEN.CTKHUYENMAI]: any;
  [APP_SCREEN.CAUHOITHUONGGAP]: any;
  [APP_SCREEN.LICHSUDIEM]: any;
  [APP_SCREEN.MOTATHEMDIEM]: any;
  [APP_SCREEN.MANCHITIET]: any;
  [APP_SCREEN.ABOUTUS]: any;
  [APP_SCREEN.KHAOSATTRUCTUYEN]: any;
  [APP_SCREEN.KETQUAHOCTAPSV]: any;
  [APP_SCREEN.CHITIETDIEMCONG]: any;
  [APP_SCREEN.NOIDUNGBUOIHOC]: any;
  [APP_SCREEN.TAOTHONGBAOGIANGVIEN]: any;
  [APP_SCREEN.THONGBAOGV]: any;
  [APP_SCREEN.THONGTINSINHVIEN]: {
    idLHP: string;
    sinhVien: any;
    onRefresh: () => void;
  };
  [APP_SCREEN.THONGTINSINHVIENLHC]: { listHS: SinhVienLHCProps[] };
  [APP_SCREEN.LOPHANHCHINHGV]: any;
  [APP_SCREEN.CHITIETLOPHC]: any;
  [APP_SCREEN.THONGTINCHUNGLOPHC]: any;
  [APP_SCREEN.THONGKEGIOGIANG]: any;
  [APP_SCREEN.LICHTUANHOCVIEN]: any;
  [APP_SCREEN.THACMACDIEMLTC]: any;
  [APP_SCREEN.GUIBANCHINHSUA]: any;
  [APP_SCREEN.SEARCHTCNSCANBO]: any;
  [APP_SCREEN.ADDTABLE]: {
    item: CauHinhLoaiHinhProps;
    getData: (e: any, index?: number) => void;
    delItem: (index: number) => void;
    dataInit?: any;
    index?: number;
  };
  [APP_SCREEN.VIEWTABLE]: {
    item: CauHinhLoaiHinhProps;
    dataInit?: any;
  };
  [APP_SCREEN.KHAIBAOQUYTRINH]: undefined;
  [APP_SCREEN.ADDEVENTCALENDAR]?: {
    onRefresh?: () => void;
    item?: any;
    xemChiTiet?: boolean;
  };
  [APP_SCREEN.THONGBAO]: {
    isFromOutside?: boolean;
    getAmountUnread?: () => void;
  };
  [APP_SCREEN.CACBUOCKHAIBAO]: {
    data?: DSKhaiBaoProps | undefined;
    banGhiDon: LichSuKhaiBaoProps;
    onIndexChange?: (e: number) => void;
    refreshLichSu?: () => void;
  };
  [APP_SCREEN.TOCHUCNHANSU]: any;
  [APP_SCREEN.QUATRINHCUDICONGTAC]: any;
  [APP_SCREEN.QUATRINHCUDIDTBD]: any;
  [APP_SCREEN.KEKHAITAISAN]: any;
  [APP_SCREEN.KEHOACHNAM]: any;
  [APP_SCREEN.DANHGIABUOIHOC]: any;
  [APP_SCREEN.LICHSUDAYBU]: any;
  [APP_SCREEN.BANGCHAMCONG]: any;
  [APP_SCREEN.KYTUCXA]: any;
  [APP_SCREEN.DANGKYKYTUCXA]: any;
  [APP_SCREEN.ADDDANGKYKYTUCXA]: any;
  [APP_SCREEN.COSOVATCHAT]: any;
  [APP_SCREEN.TAISANVATTU]: any;
  [APP_SCREEN.CHITIETTAISANVATTU]: any;
  [APP_SCREEN.KIEMKETAISAN]: any;
  [APP_SCREEN.PHONGKIEMKETAISAN]: any;
  [APP_SCREEN.CHITIETKEHOACHHOATDONG]: any;
  [APP_SCREEN.DSKEHOACHHOATDONG]: any;
  [APP_SCREEN.KEHOACHHOATDONG]: any;
  [APP_SCREEN.DSTAISANKIEMKE]: any;
  [APP_SCREEN.SEARCHQLDTSINHVIEN]: any;
  [APP_SCREEN.CONGVIEC]: any;
  [APP_SCREEN.CHITIETCONGVIEC]: any;
  [APP_SCREEN.LICHSUTIENDOCONGVIEC]: any;
  [APP_SCREEN.THEMMOIQUATRINHCUDIDTBD]: any;
  [APP_SCREEN.HOPDONG]: any;
  [APP_SCREEN.CHITIETHOPDONG]: any;
  [APP_SCREEN.BANGLAMTHEMGIO]: any;
  [APP_SCREEN.DALUU]: any;
  [APP_SCREEN.DANHSACHDONXINNGHI]: any;
  [APP_SCREEN.CHITIETPHIEUDIEM]: any;
  [APP_SCREEN.THEMMOIMINHCHUNG]: any;
  [APP_SCREEN.SUKIENDATHAMGIA]: any;
  [APP_SCREEN.KHAOSATSUKIEN]: any;
  [APP_SCREEN.THEMMOILICHLAMTHEMGIO]: any;
  [APP_SCREEN.THEMMOIDANHSACHLAMTHEM]: any;
  [APP_SCREEN.THEMMOIDANHSACHHOCLIEU]: any;
  [APP_SCREEN.BINHLUAN]: any;
  [APP_SCREEN.CHITIETBAIDANG]: any;
  [APP_SCREEN.CHITIETBAITAP]: any;
  [APP_SCREEN.KHAOSATBAITAP]: any;
  [APP_SCREEN.BAITAPVENHASINHVIEN]: any;
  [APP_SCREEN.THONGTINBAITAP]: any;
};

export type StackScreenProps<T extends keyof RootStackParamList> =
  RNStackScreenProps<RootStackParamList, T>;
